# Generated by Django 3.2.5 on 2021-08-22 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0002_auto_20210728_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CAName', models.CharField(max_length=50)),
                ('CAImage', models.ImageField(blank=True, null=True, upload_to='category/')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('CAParent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRName', models.CharField(max_length=15, verbose_name='Title')),
                ('PRDesc', models.TextField(verbose_name='Description ')),
                ('PRPrice', models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name=' Price')),
                ('PRImage', models.ImageField(blank=True, null=True, upload_to='static/site_static/images/product-detail', verbose_name='Product Image')),
                ('PRContact', models.IntegerField(blank=True, null=True, verbose_name='Conatct Number')),
                ('PRAddress', models.CharField(blank=True, max_length=30, null=True, verbose_name='Address')),
                ('PRIsNew', models.BooleanField(default=False, verbose_name='New')),
                ('PRIsUsed', models.BooleanField(default=True, verbose_name='Used')),
                ('PRCreate', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('PRSold', models.BooleanField(default=False, verbose_name='Sold')),
                ('PRSlug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('PRBrand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.brand', verbose_name='Brand')),
                ('PRCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procat', to='product.category', verbose_name='Category')),
                ('PRuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_name')),
            ],
            options={
                'ordering': ['-PRCreate'],
            },
        ),
        migrations.CreateModel(
            name='ProductNative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRAlternatives', models.ManyToManyField(related_name='Alternatives_Product', to='product.Product')),
                ('PRNName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Main_Product', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRImage', models.ImageField(upload_to='static/site_static/images/product-detail', verbose_name='Product Images')),
                ('PRImgProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
