# Generated by Django 3.2.5 on 2021-08-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRSold',
            field=models.BooleanField(default=False, null=True, verbose_name='Sold'),
        ),
    ]
