# Generated by Django 3.2.5 on 2021-08-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_prsold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRSold',
            field=models.BooleanField(default=False, verbose_name='Sold'),
        ),
    ]
