# Generated by Django 3.2.5 on 2021-08-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_prsold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BLSTUser', models.CharField(max_length=50, verbose_name='Name')),
                ('BLSTPhone', models.IntegerField(verbose_name='phone')),
                ('BLSTAddress', models.CharField(max_length=50, null=True, verbose_name='Address')),
            ],
        ),
    ]
