# Generated by Django 3.2.5 on 2021-08-22 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_blacklist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blacklist',
        ),
    ]
