# Generated by Django 3.2.5 on 2021-08-22 03:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/site_static/images/profile-images', verbose_name='Image')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='phone')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('join_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Join Date')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
