# Generated by Django 3.1.7 on 2021-04-06 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BRNDProductName', models.CharField(max_length=50, verbose_name='Brand name')),
                ('BRNDProductDis', models.TextField(blank=True, max_length=100, null=True, verbose_name='Brand Desc')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VarName', models.CharField(max_length=30, verbose_name='Variant Name')),
                ('VarDes', models.TextField(blank=True, max_length=100, null=True, verbose_name='Variant Descri')),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variants',
            },
        ),
    ]
